/**
 * Created by user on 05.01.17.
 */
var appService,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

require('../Class/player.js');

appService = (function() {
  function appService(Restangular, player, localStorage) {
    this.Restangular = Restangular;
    this.player = player;
    this.localStorage = localStorage;
    this.init = bind(this.init, this);
    this.inited = false;
  }

  appService.prototype.init = function() {
    this.player.init();
    return this.Restangular.one('api/v1/companies/').get().then((function(_this) {
      return function(res) {
        return _this.companies = res.results;
      };
    })(this));
  };

  return appService;

})();

angular.module('app').service('gameService', ['Restangular', 'Player', '$localStorage', appService]);

// ---
// generated by coffee-script 1.9.2