/**
 * Created by user on 05.01.17.
 */
var gameCtrl, tpl,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

tpl = require('./game.jade');

require('../Components/playerInfo/playerInfo.js');

require('./gameService.js');

require('./companyList/companyList.js');

require('./companyDetail/companyDetail.js');

require('./profile/profile.js');

gameCtrl = (function() {
  function gameCtrl(service) {
    this.service = service;
    this.$routerOnActivate = bind(this.$routerOnActivate, this);
    this.gameName = "Основной экран";
  }

  gameCtrl.prototype.$routerOnActivate = function(next) {
    return this.service.init();
  };

  return gameCtrl;

})();

angular.module('app').component('game', {
  template: tpl(),
  controller: ['gameService', gameCtrl],
  controllerAs: 'ctrl',
  bindings: {
    $router: '<'
  },
  $routeConfig: [
    {
      path: '/',
      name: 'CompanyList',
      component: 'companyList',
      useAsDefault: true
    }, {
      path: '/company-detail',
      name: 'CompanyDetail',
      component: 'companyDetail'
    }, {
      path: '/profile',
      name: 'Profile',
      component: 'profile'
    }
  ]
});

// ---
// generated by coffee-script 1.9.2