/**
 * Created by user on 05.01.17.
 */
var playerInfoCtrl, tpl,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

tpl = require('./playerInfo.jade');

playerInfoCtrl = (function() {
  function playerInfoCtrl(Restangular) {
    this.Restangular = Restangular;
    this.goToProfile = bind(this.goToProfile, this);
    this.$onInit = bind(this.$onInit, this);
  }

  playerInfoCtrl.prototype.$onInit = function() {};

  playerInfoCtrl.prototype.goToProfile = function() {
    return this.router.navigate(['Profile']);
  };

  return playerInfoCtrl;

})();

angular.module('app').component('playerInfo', {
  template: tpl(),
  controller: ['Restangular', playerInfoCtrl],
  controllerAs: 'ctrl',
  bindings: {
    player: '<',
    router: '<'
  }
});

// ---
// generated by coffee-script 1.9.2