# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
