# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_auto_20160807_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_rel_Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='managers.Answer')),
                ('question', models.ManyToManyField(to='managers.Question')),
            ],
        ),
    ]
