# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-25 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_remove_person_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='managers.Company'),
        ),
    ]
