# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_auto_20160927_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_path',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
