# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0011_auto_20160927_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='related_companies',
            field=models.ManyToManyField(to='managers.Company'),
        ),
        migrations.AlterField(
            model_name='person',
            name='companyDetail',
            field=models.CharField(max_length=250),
        ),
    ]
