# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0012_auto_20160928_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='related_companies',
            field=models.ManyToManyField(null=True, to='managers.Company'),
        ),
    ]
