# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0013_auto_20160928_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image_path',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
