# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0014_auto_20160928_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyDetail',
            name='description',
            field=models.CharField(default=None, max_length=350, null=True),
        ),
    ]
