# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-01 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0015_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyDetail',
            name='size',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
