/**
 * Created by user on 05.01.17.
 */
var companyListCtrl, tpl,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

require('../gameService.ts');

tpl = require('./companyList.jade');

companyListCtrl = (function() {
  function companyListCtrl(service) {
    this.service = service;
    this.goToCompany = bind(this.goToCompany, this);
  }

  companyListCtrl.prototype.goToCompany = function(id) {
    return this.$router.navigate([
      'CompanyDetail', {
        companyId: id
      }
    ]);
  };

  return companyListCtrl;

})();

angular.module('app').component('companyList', {
  template: tpl(),
  controller: ['gameService', companyListCtrl],
  controllerAs: 'ctrl',
  bindings: {
    $router: '<'
  }
});

// ---
// generated by coffee-script 1.9.2