/**
 * Created by user on 05.01.17.
 */
var Company,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Company = (function() {
  function Company(Restangular, localStorage) {
    this.Restangular = Restangular;
    this.localStorage = localStorage;
    this.selectCurrent = bind(this.selectCurrent, this);
    this.current = {};
    this.items = [];
  }

  Company.prototype.selectCurrent = function(id) {
    return this.Restangular.one('api/v1/companies/', id).get().then((function(_this) {
      return function(res) {
        _this.current = res;
      };
    })(this));
  };

  return Company;

})();

angular.module('app').service('Company', ['Restangular', '$localStorage', Company]);

module.exports = Company;

// ---
// generated by coffee-script 1.9.2