/**
 * Created by user on 05.01.17.
 */
var Npc;

require('../Class/player.ts');

Npc = require('../Class/npc.ts');

angular.module('app').factory('Person', [
  function() {
    return function(res) {
      var person;
      if (res.type === 'player') {
        person = Player();
      } else if (res.type === 'npc') {
        person = new Npc();
      }
      return person;
    };
  }
]).factory('NpcFactory', [
  'Restangular', '$q', function() {
    return function(Restangular, q) {
      this.Restangular = Restangular;
      this.q = q;

      var npc = new Npc;
      var s = npc.initNew(this.Restangular, this.q);
      return s;
    };
  }
]);

// ---
// generated by coffee-script 1.9.2