/**
 * Created by user on 05.01.17.
 */
var menuCtrl, modalTpl, tpl,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

tpl = require('./menu.jade');

modalTpl = require('./modal.jade');

require('./modal.js');

menuCtrl = (function() {
  function menuCtrl(uibModal, Restangular, localStorage, cookies) {
    this.uibModal = uibModal;
    this.Restangular = Restangular;
    this.localStorage = localStorage;
    this.cookies = cookies;
    this.help = bind(this.help, this);
    this.deletePerson = bind(this.deletePerson, this);
    this.goToGame = bind(this.goToGame, this);
    this.$onInit = bind(this.$onInit, this);
    this.canSeeEditor = false;
  }

  menuCtrl.prototype.$onInit = function() {
    this.Restangular.one('api/v1/my/').get().then((function(_this) {
      return function(res) {
        _this.localStorage.user = {
          id: res.user_id
        };
        return _this.canSeeEditor = res.see_editor;
      };
    })(this));
    return this.Restangular.one('api/v1/persons').get().then((function(_this) {
      return function(res) {
        _this.players = res;
      };
    })(this));
  };

  menuCtrl.prototype.goToGame = function(playerId) {
    this.localStorage.player = {
      id: playerId
    };
    return this.$router.navigate(['Game']);
  };

  menuCtrl.prototype.deletePerson = function(id) {
    var s;
    s = this.cookies.getAll();
    return this.Restangular.one('api/v1/persons/' + id).remove('', {
      'X-CSRFToken': s.csrftoken
    }).then((function(_this) {
      return function(res) {
        return _this.$onInit();
      };
    })(this));
  };

  menuCtrl.prototype.help = function() {
    return this.modal = this.uibModal.open({
      controller: 'modalCtrl',
      controllerAs: '$ctrl',
      template: modalTpl()
    });
  };

  return menuCtrl;

})();

angular.module('app').component('menu', {
  template: tpl(),
  controller: ['$uibModal', 'Restangular', '$localStorage', '$cookies', menuCtrl],
  controllerAs: 'ctrl',
  bindings: {
    $router: '<'
  }
}).value('$routerRootComponent', 'app');

// ---
// generated by coffee-script 1.9.2
